[project]
name = "djangoforum"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0",
    "django-ckeditor-5>=0.2.18",
    "environs>=14.5.0",
    "pillow>=12.0.0",
]
